export const weeks = [
  { value: 0, label: 'Sunday' },
  { value: 1, label: 'Monday' },
  { value: 2, label: 'Tuesday' },
  { value: 3, label: 'Wednesday' },
  { value: 4, label: 'Thursday' },
  { value: 5, label: 'Friday' },
  { value: 6, label: 'Saturday' },
];

export const states = [
  { value: 'AN', label: 'ANDAMAN AND NICOBAR ISLANDS' },
  { value: 'AP', label: 'ANDHRA PRADESH' },
  { value: 'AR', label: 'ARUNACHAL PRADESH' },
  { value: 'AS', label: 'ASSAM' },
  { value: 'BR', label: 'BIHAR' },
  { value: 'CG', label: 'CHANDIGARH' },
  { value: 'CH', label: 'CHHATTISGARH' },
  { value: 'DH', label: 'DADRA AND NAGAR HAVELI' },
  { value: 'DD', label: 'DAMAN AND DIU' },
  { value: 'DL', label: 'DELHI' },
  { value: 'GA', label: 'GOA' },
  { value: 'GJ', label: 'GUJARAT' },
  { value: 'HR', label: 'HARYANA' },
  { value: 'HP', label: 'HIMACHAL PRADESH' },
  { value: 'JK', label: 'JAMMU AND KASHMIR' },
  { value: 'JH', label: 'JHARKHAND' },
  { value: 'KA', label: 'KARNATAKA' },
  { value: 'KL', label: 'KERALA' },
  { value: 'LD', label: 'LAKSHADWEEP' },
  { value: 'MP', label: 'MADHYA PRADESH' },
  { value: 'MH', label: 'MAHARASHTRA' },
  { value: 'MN', label: 'MANIPUR' },
  { value: 'ML', label: 'MEGHALAYA' },
  { value: 'MZ', label: 'MIZORAM' },
  { value: 'NL', label: 'NAGALAND' },
  { value: 'OR', label: 'ODISHA' },
  { value: 'PY', label: 'PUDUCHERRY' },
  { value: 'PB', label: 'PUNJAB' },
  { value: 'RJ', label: 'RAJASTHAN' },
  { value: 'SK', label: 'SIKKIM' },
  { value: 'TN', label: 'TAMIL NADU' },
  { value: 'TS', label: 'TELANGANA' },
  { value: 'TR', label: 'TRIPURA' },
  { value: 'UK', label: 'UTTARAKHAND' },
  { value: 'UP', label: 'UTTAR PRADESH' },
  { value: 'WB', label: 'WEST BENGAL' },
];

export const degrees = [
  {
    value: 'Diploma in Veterinary Science [DVSc]',
    label: 'Diploma in Veterinary Science [DVSc]',
  },
  {
    value: 'Bachelor of Veterinary Science [BVSc]',
    label: 'Bachelor of Veterinary Science [BVSc]',
  },
];
